on:
  push:
    branches:
      - develop

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: auto create pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "develop"
          destination_branch: "master"
          pr_title: "【mainマージ】${{ github.event.head_commit.message }}"
          pr_body: ""
