on:
  push:
    branches:
      - develop

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: auto create pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: 'develop'
          destination_branch: "main"
          pr_title: "mainマージ"
          pr_body: ""
          pr_reviewer: "koyamann/mp-programmers"
